include:
  - ./airflow/docker-compose.yml

services:

  mongodb:
    image: "mongo:latest"
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672

  minio:
    image: minio/minio:RELEASE.2023-11-06T22-26-08Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  rabbitmq-to-minio:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - minio

  rabbitmq-to-mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    depends_on:
      - rabbitmq
      - mongodb

volumes:
  mongodb-data: